### ISSUE TITLE
Swift Bridge

### ISSUE THREAD

**Issue by marquesjordan** [gwenoleR/react-native-sinch-voip#1]
Hi this is great and much needed. Is there a way you can help with the setup process with the SDK and the swift bridge to get your package working?

**Comment by gwenoleR** [comment]
Hi !
To setup the bridge just create an empty Swift file from Xcode, and he should ask you if you want to create a Bridge. Click yes and voilà. Should work.
Tell me if it is working, and if not, can you give me more informations ?

**Comment by marquesjordan** [comment]
Do I need to add the SDK? If so where and what steps once I add it? Does
not connect calls for me.

@gwenoleR  Is there any possible way we can connect to help me get setup?
